#install packages from CRAN
install.packages(pkgs = c('here',
                          'ggplot2',
                          'matrixStats',
                          'devtools',
                          'knitr',
                          'patchwork',
                          'BiocManager'),
                 ask = FALSE,
                 dependencies = TRUE,
                 checkBuilt = TRUE,
                 repos= 'http://cran.rstudio.com/')

#install bioconductor packages                 
BiocManager::install( pkgs = c('DESeq2',
                                'RColorBrewer',
                                'ComplexHeatmap',
                                'GenomeInfoDb',
                                'GenomicRanges',
                                'Biobase',
                                'IRanges',
                                'XVector',
                                'Biostrings',
                                'GenomicRanges',
                                'RhtsLib',
                                'Rsamtools',
                                'SummarizedExperiment',
                                'KEGGREST',
                                'annotate',
                                'GenomicAlignments',
                                'AnnotationDbi',
                                'org.Mm.eg.db',
                                'GO.db',
                                'goseq',
                                'biomart',
                                'dearseq',
                                'limma'))